// Letter-specific instructions for more precise AI generation

const LETTER_HINTS = {
  A: 'Triangle shape with apex at top-center, two diagonal strokes meeting at the top, horizontal crossbar in the middle',
  B: 'Vertical stem on the left, two bowls (upper smaller, lower larger) on the right side',
  C: 'Open curve on the right side, opening faces right. Single stroke from top-right curving around to bottom-right',
  D: 'Vertical stem on the left, one large bowl on the right side',
  E: 'Vertical stem on the left, three horizontal arms: top, middle, bottom. Middle arm slightly shorter',
  F: 'Like E but without the bottom arm. Vertical stem, top arm, and middle arm',
  G: 'Like C but with a horizontal spur on the lower right, connecting back toward center',
  H: 'Two vertical stems connected by a horizontal crossbar in the middle',
  I: 'Simple vertical stroke with optional serifs at top and bottom',
  J: 'Vertical stroke that curves left at the bottom, like a fish hook',
  K: 'Vertical stem on the left, two diagonal strokes from the middle going upper-right and lower-right',
  L: 'Vertical stroke down, then horizontal stroke to the right at the bottom',
  M: 'Two vertical outer strokes with a V-shaped dip in the middle connecting them at the top',
  N: 'Vertical left stroke, diagonal stroke going up-right, vertical right stroke',
  O: 'Perfect oval/ellipse shape. Must have an outer contour and inner counter (hole)',
  P: 'Vertical stem on the left, one bowl on the upper right side only',
  Q: 'Like O with a short diagonal tail stroke extending from the bottom-right',
  R: 'Like P but with a diagonal leg extending from the bowl down to the right',
  S: 'Double curve: top curve bulging right, bottom curve bulging left, like a snake',
  T: 'Horizontal stroke at top, vertical stem descending from the center',
  U: 'Two vertical strokes connected by a curved bottom',
  V: 'Two diagonal strokes meeting at a point at the bottom center',
  W: 'Two V shapes side by side, creating a wide M-like bottom',
  X: 'Two diagonal strokes crossing in the center',
  Y: 'Two diagonal strokes from top merging into a single vertical stem at center',
  Z: 'Horizontal top stroke, diagonal going down-left, horizontal bottom stroke',

  a: 'Single-story: round bowl on the right with a vertical stem on the right side, open at top',
  b: 'Vertical stem on the left (tall, to cap height), round bowl on the lower right',
  c: 'Open curve, like C but smaller. Opening faces right',
  d: 'Round bowl on the lower left, vertical stem on the right (tall, to cap height)',
  e: 'Like c but with a horizontal bar in the middle, extending from the left side',
  f: 'Tall vertical stem with a curved hook at top and a horizontal arm on the left at x-height',
  g: 'Like lower-case o but with a descender tail that curves left at the bottom',
  h: 'Tall vertical stem on the left, shorter rounded shoulder on the upper right connecting to a short vertical',
  i: 'Short vertical stem with a dot (tittle) above it',
  j: 'Like i but with a descender tail curving left below the baseline',
  k: 'Tall vertical stem, two diagonal strokes from middle going upper-right and lower-right',
  l: 'Simple tall vertical stroke',
  m: 'Two rounded shoulders side by side, connecting to a vertical stem on the left',
  n: 'One rounded shoulder on the right connecting to a vertical stem on the left',
  o: 'Small oval shape, must have outer contour and inner counter',
  p: 'Round bowl on the upper right, vertical stem descending below baseline on the left',
  q: 'Round bowl on the upper left, vertical stem descending below baseline on the right',
  r: 'Vertical stem with a small shoulder curve at the top right',
  s: 'Small version of S: double curve shape',
  t: 'Short vertical stem with a horizontal crossbar near the top, stem extends slightly above crossbar',
  u: 'Two short verticals connected by a curved bottom',
  v: 'Two diagonal strokes meeting at a point at the bottom',
  w: 'Two connected v shapes, wider than v',
  x: 'Two diagonal strokes crossing in the center',
  y: 'Two diagonals meeting at center, then a descender tail going below baseline',
  z: 'Horizontal top, diagonal going down-left, horizontal bottom',

  '0': 'Oval shape with a slight inward curve on the right side (oldstyle), inner counter hole',
  '1': 'Vertical stem with a small flag/serif at top left',
  '2': 'Curve at top going right, then diagonal going down-left to baseline, horizontal bottom',
  '3': 'Two stacked right-facing curves, top smaller than bottom',
  '4': 'Vertical stroke on right, diagonal from top-left to middle-right, horizontal crossbar',
  '5': 'Horizontal top stroke, vertical going down then curving right into a belly',
  '6': 'Curve from top that wraps around into a full circle at the bottom',
  '7': 'Horizontal top stroke, diagonal going down-left',
  '8': 'Two circles stacked, top slightly smaller than bottom',
  '9': 'Full circle at top, then a descender tail going down',
};

export function getLetterHint(letter) {
  return LETTER_HINTS[letter] || `Standard recognizable form of the letter ${letter}`;
}
